# Generated by Django 6.0.4 on 2026-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(default='Alterar', max_length=85),
        ),
    ]
