# Generated by Django 6.0.4 on 2026-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_usuario_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=85),
        ),
    ]
