# Generated by Django 6.0.4 on 2026-04-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeFabril',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_autor', models.CharField(max_length=125)),
                ('forma_de_participacao', models.CharField(choices=[('IND', 'Individual'), ('GRP', 'Grupo')], default='IND', max_length=3, verbose_name='forma_de_participacao')),
                ('componentes_equipe', models.TextField(blank=True, null=True, verbose_name='Componentes da equipe')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_problema', models.CharField(max_length=400)),
                ('impacto_problema', models.CharField(max_length=300)),
                ('causa_problema', models.CharField(max_length=250)),
                ('descricao_ideia', models.CharField(max_length=500)),
                ('como_a_ideia_resolve_problema', models.CharField(max_length=500)),
                ('participacao_implementacao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='participacao_implementacao')),
                ('outros_beneficios', models.CharField(blank=True, max_length=255, null=True)),
                ('ganhos_esperados', models.CharField(max_length=250)),
                ('necessidades_ideia', models.CharField(max_length=250)),
                ('valor_estimado_ideia', models.CharField(max_length=100)),
                ('prazo_estimado_ideia', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('beneficios', models.ManyToManyField(to='respostas.beneficio')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento_ideia', to='respostas.departamento')),
                ('unidade_fabril', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade_fabril_ideia', to='respostas.unidadefabril')),
            ],
        ),
    ]
