# Generated by Django 6.0.4 on 2026-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficio',
            options={'verbose_name': 'Benefício', 'verbose_name_plural': 'Benefícios'},
        ),
        migrations.AlterModelOptions(
            name='ideia',
            options={'verbose_name': 'Ideia', 'verbose_name_plural': 'Ideias cadastradas'},
        ),
        migrations.AlterModelOptions(
            name='unidadefabril',
            options={'verbose_name': 'Unidade Fabril', 'verbose_name_plural': 'Unidades Fabris'},
        ),
        migrations.AlterField(
            model_name='ideia',
            name='componentes_equipe',
            field=models.TextField(blank=True, null=True, verbose_name='Integrantes da equipe'),
        ),
    ]
