# Generated by Django 6.0.4 on 2026-04-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0002_alter_beneficio_options_alter_ideia_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideia',
            old_name='componentes_equipe',
            new_name='integrantes_equipe',
        ),
    ]
