# Generated by Django 6.0.4 on 2026-04-27 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0003_rename_componentes_equipe_ideia_integrantes_equipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=85)),
            ],
        ),
        migrations.RemoveField(
            model_name='ideia',
            name='integrantes_equipe',
        ),
        migrations.AddField(
            model_name='ideia',
            name='integrantes_equipe',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Integrantes da equipe'),
        ),
    ]
