# Generated by Django 6.0.4 on 2026-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0004_funcionario_remove_ideia_integrantes_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideia',
            name='causa_problema',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='descricao_ideia',
            field=models.CharField(max_length=1300),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='descricao_problema',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='ganhos_esperados',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='impacto_problema',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='necessidades_ideia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='prazo_estimado_ideia',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='valor_estimado_ideia',
            field=models.CharField(max_length=300),
        ),
    ]
