# Generated by Django 6.0.4 on 2026-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0005_alter_ideia_causa_problema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideia',
            name='descricao_ideia',
            field=models.CharField(max_length=1400),
        ),
    ]
