# Generated by Django 6.0.4 on 2026-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0006_alter_ideia_descricao_ideia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='usuario_remetente_ideia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
