# Generated by Django 6.0.4 on 2026-05-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0007_ideia_usuario_remetente_ideia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='status_ideia',
            field=models.CharField(blank=True, default='Nova', max_length=100, null=True),
        ),
    ]
