# Generated by Django 6.0.4 on 2026-08-24 19:48

import django.core.validators
import respostas.models
import respostas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0008_ideia_status_ideia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='documento',
            field=models.FileField(blank=True, help_text='PDF, Word, Excel, PowerPoint, CSV ou TXT de até 10 MB.', max_length=255, upload_to=respostas.models.caminho_documento_ideia, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'csv', 'txt'], message='Formato não aceito. Envie PDF, Word, Excel, PowerPoint, CSV ou TXT.'), respostas.validators.valida_tamanho_anexo], verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='ideia',
            name='documento_nome_original',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='ideia',
            name='foto',
            field=models.ImageField(blank=True, help_text='JPG, PNG ou WEBP de até 10 MB.', max_length=255, upload_to=respostas.models.caminho_foto_ideia, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Envie uma imagem nos formatos JPG, PNG ou WEBP.'), respostas.validators.valida_tamanho_anexo], verbose_name='Foto'),
        ),
    ]
