# Generated by Django 6.0.4 on 2026-08-24 19:58

import django.core.validators
import django.db.models.deletion
import respostas.models
import respostas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0009_ideia_documento_ideia_documento_nome_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideia',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='ideia',
            name='documento_nome_original',
        ),
        migrations.RemoveField(
            model_name='ideia',
            name='foto',
        ),
        migrations.CreateModel(
            name='DocumentoIdeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(blank=True, editable=False, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(max_length=255, upload_to=respostas.models.caminho_documento_ideia, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'csv', 'txt'], message='Formato não aceito. Envie PDF, Word, Excel, PowerPoint, CSV ou TXT.'), respostas.validators.valida_tamanho_anexo])),
                ('ideia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='respostas.ideia')),
            ],
            options={
                'verbose_name': 'Documento da ideia',
                'verbose_name_plural': 'Documentos da ideia',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FotoIdeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(blank=True, editable=False, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ImageField(max_length=255, upload_to=respostas.models.caminho_foto_ideia, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Envie uma imagem nos formatos JPG, PNG ou WEBP.'), respostas.validators.valida_tamanho_anexo])),
                ('ideia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='respostas.ideia')),
            ],
            options={
                'verbose_name': 'Foto da ideia',
                'verbose_name_plural': 'Fotos da ideia',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
