# Generated by Django 6.0.4 on 2026-08-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0010_remove_ideia_documento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideia',
            options={'permissions': [('ver_todas_ideias', 'Pode ver todas as ideias enviadas')], 'verbose_name': 'Ideia', 'verbose_name_plural': 'Ideias cadastradas'},
        ),
    ]
